
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { UserProvider } from "@/hooks/user-context";
import { NotificationManagerProvider } from "@/hooks/notification-context";
import { GEOProvider } from "@/hooks/geo-context";
import "./globals.css";
import Header from "../components/header/page";
import Notifications from "../components/notification/page";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GEOProvider>
          <UserProvider>
            <Script
              src="https://api-maps.yandex.ru/2.1/?lang=ru_RU"
              strategy="beforeInteractive"
            />
            <Script
              src="https://yastatic.net/s3/mapsapi-jslibs/heatmap/0.0.1/heatmap.min.js"
              strategy="beforeInteractive"
            />

            <NotificationManagerProvider>
              <Header />
              <Notifications />
              {children}
            </NotificationManagerProvider>
          </UserProvider>
        </GEOProvider>
      </body>
    </html>
  );
}
