# Generated by Django 5.2.6 on 2025-09-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reports_penalties_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='file',
            field=models.FileField(unique=True, upload_to=''),
        ),
    ]
