# Generated by Django 5.2.6 on 2025-09-23 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_reports_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TowTrucks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tow_truck_in_line', models.IntegerField()),
                ('count_departures', models.IntegerField()),
                ('count_evacuations', models.IntegerField()),
                ('summary_of_parking_lot', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reports')),
            ],
        ),
    ]
