# Generated by Django 5.2.6 on 2025-09-23 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_route_evacuationroute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evacuationroute',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AlterModelOptions(
            name='penalties',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='towtrucks',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='evacuationroute',
            name='Reports',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.reports'),
            preserve_default=False,
        ),
    ]
