# Generated by Django 5.2.6 on 2025-09-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_evacuationroute_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evacuationroute',
            old_name='Reports',
            new_name='report',
        ),
    ]
