# Generated by Django 5.2.6 on 2025-09-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_reports_evacuationroute_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evacuationroute',
            name='month',
            field=models.TextField(),
        ),
    ]
