# Generated by Django 5.2.6 on 2025-09-23 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_evacuationroute_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numPP', models.IntegerField()),
                ('address', models.TextField()),
                ('type', models.TextField()),
                ('year', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reports')),
            ],
            options={
                'ordering': ['-numPP'],
            },
        ),
    ]
