# Generated by Django 5.2.6 on 2025-09-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_trafficlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlight',
            name='numPP',
            field=models.IntegerField(unique=True),
        ),
    ]
