# Generated by Django 5.2.6 on 2025-09-24 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_trafficlight_numpp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.TextField()),
                ('point_FPSR', models.TextField()),
                ('statistical_factor', models.TextField()),
                ('count', models.FloatField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reports')),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
    ]
