# Generated by Django 5.2.6 on 2025-09-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageForMerits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='merits/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Merits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_first_block', models.FileField(upload_to='merits/logo/')),
                ('title', models.CharField(max_length=10, unique=True)),
                ('decode', models.TextField()),
                ('purposes', models.TextField()),
                ('logo_second_block', models.FileField(upload_to='merits/logo/')),
                ('parents_name', models.TextField()),
                ('parents_phone', models.TextField()),
                ('parents_email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('images_first_block', models.ManyToManyField(related_name='images_first_block', to='core.imageformerits')),
                ('images_second_block', models.ManyToManyField(related_name='images_second_block', to='core.imageformerits')),
            ],
        ),
    ]
