# Generated by Django 5.2.7 on 2025-10-16 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_imageformerits_merits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('speed', models.FloatField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.car')),
                ('detector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.detector')),
            ],
        ),
        migrations.CreateModel(
            name='DetectorRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('detectorEnd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detectorEnd', to='core.detector')),
                ('detectorStart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detectorStart', to='core.detector')),
            ],
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_interval', models.CharField(choices=[('00:00-02:00', '00:00-02:00'), ('02:00-04:00', '02:00-04:00'), ('04:00-06:00', '04:00-06:00'), ('06:00-08:00', '06:00-08:00'), ('08:00-10:00', '08:00-10:00'), ('10:00-12:00', '10:00-12:00'), ('12:00-14:00', '12:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('22:00-24:00', '22:00-24:00')], max_length=20)),
                ('detections', models.ManyToManyField(to='core.detection')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='workloads',
            field=models.ManyToManyField(to='core.workload'),
        ),
    ]
