# Generated by Django 5.2.7 on 2025-10-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_car_detector_detection_detectorroute_workload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
